snapshot: lts-23.25

packages:
- .
# Dependency packages to be pulled from upstream that are not in the snapshot.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
extra-deps:
  - ../../

  - git: https://github.com/tusharad/ollama-haskell
    commit: 33807a3a5a507e99d92b26e245c0aed582fde581

  - git: https://github.com/MercuryTechnologies/openai
    commit: 2031a05135b892a82b461558d19b813ab67cfb8f
