name:                examples
version:             0.1.0.0
github:              "tusharad/langchain-hs/example"
license:             MIT
author:              "Tushar Adhatrao"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2026 Tushar Adhatrao"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Set of examples of Langchain-hs
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/examples#readme>

dependencies:
- base >= 4.7 && < 5
- langchain-hs
- text
- aeson
- bytestring
- mtl


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  simple-ollama:
    main:                SimpleOllama.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples

tests:
  examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples
