name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "latest"
          working-directory: "./src"

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: src/
        fail-on: warning

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  build:
    needs: generate
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
          stack-arguments: --stack-yaml ${{ matrix.stack-yaml }}
          test: false
  
  tests:
    needs: build

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
 
    - name: Installing ollama
      uses: pydantic/ollama-action@v3
      with:
        model: qwen3:0.6b

    - name: Warming up ollama models
      run: |
        ollama run qwen3:0.6b "Hey, how are you?"

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5

  docs:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json

    - name: Build docs
      working-directory: docs
      run: |
        npm ci
        npm run build
